require("config.keybinds")
require("config.globals")
require("config.lazy")

require("config.lsp")
require("config.lualine")
require("config.bufferline")
require("config.neo-tree")
require("config.autocmd")
require("config.conform")
